# Generated by Django 6.0.3 on 2026-04-19 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='hotel_name',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='travel.hotel'),
            preserve_default=False,
        ),
    ]
