# Generated by Django 6.0.3 on 2026-04-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_package_hotel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(upload_to='package_image/'),
        ),
    ]
