# Generated by Django 6.0.3 on 2026-04-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_booking_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='populer_hotel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='populer_tour',
            field=models.BooleanField(default=False),
        ),
    ]
