# Generated by Django 6.0.3 on 2026-05-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_user_auto_confirm_bookings_user_bookings_reminders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_avatars/'),
        ),
    ]
