# Generated by Django 6.0.3 on 2026-05-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_user_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bookings_reminders',
            new_name='booking_reminders',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='promo_email',
            new_name='promo_emails',
        ),
    ]
