# Generated by Django 6.0.3 on 2026-05-25 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_rename_bookings_reminders_user_booking_reminders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online Payment'), ('cash', 'Cash on Arrival')], default='cash', max_length=20),
        ),
    ]
